---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hydra-cni-role
  namespace: hydra-cni
rules:
  - apiGroups: [""]
    resources: ["pods","pods/status"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hydra-cni-role-binding
  namespace: hydra-cni
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hydra-cni-role
subjects:
  - kind: ServiceAccount
    name: hydra-cni-service-account
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hydra-cni-service-account
  namespace: hydra-cni


---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    k8s-app: hydra-cni
    pod-security.kubernetes.io/enforce: privileged
  name: hydra-cni
---
apiVersion: v1
data:
  cni-conf.json: |
    {
      "name": "hydra",
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "flannel",
          "delegate": {
            "type": "bridge",
            "bridge": "hydra.0",
            "hairpinMode": true,
            "isDefaultGateway": true
          }
        },
        {
          "type": "portmap",
          "capabilities": {
            "portMappings": true
          }
        }
      ]
    }
kind: ConfigMap
metadata:
  name: hydra-cni-cfg
  namespace: hydra-cni

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: hydra-cni
  name: hydra-cni-ds
  namespace: hydra-cni
spec:
  selector:
    matchLabels:
      app: hydra-cni
  template:
    metadata:
      labels:
        app: hydra-cni
    spec:
      hostNetwork: true
      serviceAccountName: echo-bio-service-account
      initContainers:
        - name: hydra-cni-init
          image: 'busybox:latest'
          imagePullPolicy: IfNotPresent
          command:
            - cp
          args:
            - -f
            - /etc/hydra-cni/cni-conf.json
            - /etc/cni/net.d/99-hydra.conflist
          volumeMounts:
            - mountPath: /etc/cni/net.d
              name: cniconf
            - mountPath: /etc/hydra-cni
              name: hydra-cni-cfg
      containers:
        - name: hydra-cni
          command:
            - "/hydra-cni"
          args:
            - "-idx"
            - "01"
            - "-cni-conf"
            - "hydra"
            - "-events"
            - "runpodsandbox,stoppodsandbox,removepodsandbox"
          env:
            - name: CNI_PATH
              value: /opt/cni/bin
            - name: CNI_IFNAME
              value: eth99
          image: docker.io/airren/hydra-cni:latest
          imagePullPolicy: Always
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: cnipath
              mountPath: /opt/cni/bin
            - name: cniconf
              mountPath: /etc/cni/net.d
            - name: netns
              mountPath: /var/run/netns
              mountPropagation: Bidirectional
            - name: nrisock
              mountPath: /var/run/nri/nri.sock
            - name: flannel
              mountPath: /run/flannel
            - mountPath: /run/xtables.lock
              name: xtables-lock
      volumes:
        - name: cnipath
          hostPath:
            path: /opt/cni/bin
            type: Directory
        - name: cniconf
          hostPath:
            path: /etc/cni/net.d
            type: Directory
        - name: netns
          hostPath:
            path: /var/run/netns
            type: Directory
        - name: nrisock
          hostPath:
            path: /var/run/nri/nri.sock
            type: Socket
        - configMap:
            name: hydra-cni-cfg
          name: hydra-cni-cfg
        - name: flannel
          hostPath:
            path: /run/flannel/hydra-cni
            type: DirectoryOrCreate
        - hostPath:
            path: /run/xtables.lock
            type: FileOrCreate
          name: xtables-lock
