apiVersion: v1
kind: Service
metadata:
  name: sdewan
  namespace: sdewan-system
spec:
  selector:
    sdewanPurpose: base
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30080
  type: NodePort
  